In [2]:
# 0을 제거하고 단순선형회귀분석을 실시하였을 때, 결정계수를 보자
import pandas as pd
retail = pd.read_csv('../data/raw/Retail data.csv')

In [3]:
retail.head()

Month  Sales Total  Store Product Type           Item
0  2021-02-01 00:00:00            1      1  Electronics  Phone Charger
1  2021-02-01 00:00:00            5      1      Grocery         Shrimp
2  2021-02-01 00:00:00            2      1      Grocery        Noodles
3  2021-02-01 00:00:00            1      1      Grocery      King Crab
4  2021-03-01 00:00:00            1      1  Electronics       Ear Buds

In [9]:
store1 = retail[(retail['Store'] == 345) & (retail['Item'] == 'Keyboard')]

In [10]:
store1

Month  Sales Total  Store Product Type      Item
66826  2015-04-01 00:00:00            1    345  Electronics  Keyboard
66833  2017-03-01 00:00:00            1    345  Electronics  Keyboard
66848  2018-12-01 00:00:00            2    345  Electronics  Keyboard
66851  2019-03-01 00:00:00            1    345  Electronics  Keyboard
66855  2019-09-01 00:00:00            1    345  Electronics  Keyboard
66857  2019-11-01 00:00:00            1    345  Electronics  Keyboard
66863  2019-12-01 00:00:00            2    345  Electronics  Keyboard
66867  2020-08-01 00:00:00            1    345  Electronics  Keyboard

In [8]:
store1.sort_values('Month').shape

(4, 5)

In [12]:
# 대부분 판매 기록이 적음. 
# 0이 대부분 -> 
import torch
import torch.nn as nn

In [42]:
# (N, C, H, W) N : batch, C : channel
a1 = torch.rand((1, 1, 6, 4))

In [43]:
a1

tensor([[[[8.9114e-01, 5.1155e-01, 6.8896e-01, 3.4755e-01],
          [3.2920e-01, 1.0766e-01, 9.6317e-01, 7.1500e-01],
          [5.9032e-04, 5.0193e-01, 9.7518e-01, 4.9221e-01],
          [7.6147e-01, 2.1038e-01, 1.6891e-01, 7.8179e-01],
          [2.8672e-01, 6.0912e-01, 1.0061e-01, 9.7441e-01],
          [5.8569e-01, 5.4563e-02, 6.8747e-01, 9.3403e-01]]]])

In [44]:
layer1 = nn.Conv2d(1,1, kernel_size=2)

In [45]:
a2 = layer1(a1)

In [46]:
a2.shape

torch.Size([1, 1, 5, 3])

In [39]:
t1 = torch.rand(4, 4)

In [40]:
t1

tensor([[0.4417, 0.4691, 0.3894, 0.0797],
        [0.2806, 0.1864, 0.5413, 0.1471],
        [0.0603, 0.3569, 0.5777, 0.1151],
        [0.4028, 0.0068, 0.6061, 0.3355]])

In [41]:
t1.reshape(1, 1, 4, 4)

tensor([[[[0.4417, 0.4691, 0.3894, 0.0797],
          [0.2806, 0.1864, 0.5413, 0.1471],
          [0.0603, 0.3569, 0.5777, 0.1151],
          [0.4028, 0.0068, 0.6061, 0.3355]]]])

In [63]:
t1 = torch.rand(1, 1, 7848)

In [64]:
layer2 = nn.Conv1d(1, 1024, kernel_size=20)

In [65]:
k1 = layer2(t1)
print(k1.size())

torch.Size([1, 1024, 7829])


In [56]:
tmp = nn.MaxPool1d(20, stride=10)

In [67]:
tmp(k1).size()

torch.Size([1, 1024, 781])